-- CoolNasheed · supabase/setup-schema.sql — the database, without the catalogue
--
-- Generated by scripts/sql-bundle.mjs — do not edit by hand.
-- In the order it must be applied:
--
--   1. migrations/20260914120000_core.sql
--   2. migrations/20260914120100_functions.sql
--   3. migrations/20260914120300_rls.sql
--   4. migrations/20260914120400_storage.sql
--
-- Two ways to run it:
--
--   supabase link --project-ref <ref> && supabase db push      then, for the seed,
--   psql "$SUPABASE_DB_URL" -f supabase/seed.sql
--
--   …or open Supabase Studio → SQL Editor → New query, paste this file, and Run.
--      It is safe to run twice: migrations are `if not exists` / `or replace`,
--      and every seed insert is `on conflict do nothing`.


/* ================================================================ 20260914120000_core.sql */

-- CoolNasheed · core schema
--
-- Everything lives in Postgres. That is the point of using Supabase rather than a
-- server of our own: the database is the backend, Row Level Security is the access
-- control, and the only code that runs is the handful of Edge Functions that genuinely
-- need a server (see supabase/functions).
--
-- Free-tier decisions, all of them deliberate:
--   • counters (songs.plays, songs.likes, comments.amens) are maintained by triggers,
--     so a list of twenty nasheeds is one indexed query rather than twenty aggregates
--   • plays are written to play_events *and* rolled up into song_stats_daily in the
--     same call, so charts read a table of ~24×30 rows instead of every listen ever
--   • play_events is pruned after 90 days by a scheduled job; the rollups are kept,
--     which is what the charts actually need
--   • ids are text, not uuid, for songs/comments/collections: a shareable URL that says
--     /t/sng_talaa-al-badru beats one that says /t/7f3c… and costs nothing to store
--   • arrays (tags, song_ids, lines as jsonb) instead of join tables where the data is
--     read as a whole and written by one owner — fewer rows, fewer joins, same integrity

create extension if not exists pg_trgm with schema extensions;
create extension if not exists pgcrypto with schema extensions;

/* -------------------------------------------------------------------- people */

-- A profile is a publisher identity. When somebody signs up through Supabase Auth the
-- trigger below creates their row with the same id as their auth user, so
-- `profiles.id = auth.uid()` is the ownership test everywhere. The seeded catalogue
-- artists are profiles *without* an auth row: they can be followed and credited, but
-- nobody can sign in as them, because there is no credential to sign in with.
create table if not exists public.profiles (
  id          uuid primary key default gen_random_uuid(),
  handle      text not null,
  name        text not null,
  name_ar     text,
  -- what they do, e.g. "seven voices & duff" — shown on a publisher page
  tagline     text not null default '',
  bio         text not null default '',
  city        text not null default '',
  seed        text not null default '',
  accent      text not null default 'jade'
              check (accent in ('jade','gold','turq','madder','cobalt')),
  role        text not null default 'listener'
              check (role in ('listener','staff')),
  kind        text not null default 'listener'
              check (kind in ('listener','artist')),
  verified    boolean not null default false,
  created_at  timestamptz not null default now(),
  constraint handle_shape check (handle ~ '^[a-z0-9._]{3,20}$'),
  constraint name_shape check (char_length(name) between 2 and 48),
  constraint tagline_shape check (char_length(tagline) <= 120),
  constraint bio_shape check (char_length(bio) <= 280)
);

create unique index if not exists profiles_handle_key on public.profiles (handle);
create index if not exists profiles_kind_idx on public.profiles (kind);

-- handles belonging to the catalogue itself, so nobody can impersonate a reciter
create table if not exists public.reserved_handles (
  handle text primary key
);

insert into public.reserved_handles (handle) values
  ('coolnasheed'),('nur'),('admin'),('root'),('staff'),('system'),
  ('umm_sumayya'),('fajr_walker'),('ibn_al_bahr'),('quiet_minaret'),
  ('sabr_and_coffee'),('muhajir_1998'),('layla.k'),('abu_yusuf'),('zaytuna_22'),
  ('night_of_qadr'),('halabi_in_exile'),('dust_and_light'),('rawda_listener'),
  ('third_of_the_night'),('sokoto_sings'),('madrassa_dad')
on conflict do nothing;

/* --------------------------------------------------------------------- songs */

create table if not exists public.songs (
  id            text primary key default ('sng_' || substr(gen_random_uuid()::text, 1, 18)),
  owner_id      uuid references public.profiles (id) on delete cascade,
  title         text not null,
  title_ar      text,
  note          text not null default '',
  maqam         text not null
                check (maqam in ('rast','bayati','hijaz','nahawand','kurd','ajam','saba','nikriz','hijazkar','ushshaq')),
  root          integer not null check (root between 24 and 96),
  bpm           integer not null check (bpm between 30 and 240),
  voices        text not null check (voices in ('solo','duet','choir')),
  -- 16-step frame-drum pattern; null means vocals only
  duff          text check (duff is null or duff ~ '^[DT.]{16}$'),
  duff_enter    text not null default 'verse' check (duff_enter in ('intro','verse')),
  passes        integer not null default 2 check (passes between 1 and 6),
  accent        text not null default 'jade'
                check (accent in ('jade','gold','turq','madder','cobalt')),
  year          integer check (year between 600 and 2200),
  tags          text[] not null default '{}',
  -- [{tr,ar,en,note,t?}] — the lyrics, and the timings when a recording supplied them
  lines         jsonb not null default '[]'::jsonb,
  motif_bank    integer[],
  -- storage paths, not URLs: /storage/v1/object/public/nasheed-audio/<path>
  audio_path    text,
  audio_mime    text,
  audio_bytes   bigint,
  duration_ms   integer check (duration_ms is null or duration_ms between 1000 and 86400000),
  artwork_path  text,
  status        text not null default 'live' check (status in ('live','removed')),
  published_at  timestamptz not null default now(),
  created_at    timestamptz not null default now(),
  -- denormalised counters, maintained by triggers further down
  plays         integer not null default 0,
  likes         integer not null default 0,
  notes         integer not null default 0,
  constraint title_shape check (char_length(title) between 2 and 120),
  constraint note_shape check (char_length(note) <= 480),
  constraint tags_shape check (array_length(tags, 1) is null or array_length(tags, 1) <= 8),
  constraint lines_shape check (jsonb_typeof(lines) = 'array' and jsonb_array_length(lines) between 0 and 40)
);

create index if not exists songs_owner_idx on public.songs (owner_id);
create index if not exists songs_live_new_idx on public.songs (published_at desc) where status = 'live';
create index if not exists songs_live_plays_idx on public.songs (plays desc) where status = 'live';
create index if not exists songs_tags_idx on public.songs using gin (tags);
create index if not exists songs_title_trgm_idx on public.songs using gin (title extensions.gin_trgm_ops);

/* --------------------------------------------------------------- collections */

create table if not exists public.collections (
  id          text primary key default ('col_' || substr(gen_random_uuid()::text, 1, 18)),
  kind        text not null default 'album' check (kind in ('album','mukhtarat','mix')),
  title       text not null,
  title_ar    text,
  curator     text not null default 'CoolNasheed',
  blurb       text not null default '',
  seed        text not null default '',
  accent      text not null default 'jade'
              check (accent in ('jade','gold','turq','madder','cobalt')),
  tags        text[] not null default '{}',
  year        integer,
  -- ordered ids rather than a join table: a shelf is read whole and written by staff
  song_ids    text[] not null default '{}',
  owner_id    uuid references public.profiles (id) on delete set null,
  created_at  timestamptz not null default now(),
  constraint collection_title_shape check (char_length(title) between 2 and 160)
);

create index if not exists collections_kind_idx on public.collections (kind);

/* ------------------------------------------------------------------- social */

create table if not exists public.comments (
  id           text primary key default ('cmt_' || substr(gen_random_uuid()::text, 1, 18)),
  song_id      text not null references public.songs (id) on delete cascade,
  author_id    uuid not null references public.profiles (id) on delete cascade,
  text         text not null,
  at_line      integer check (at_line is null or at_line between 1 and 400),
  edited_at    timestamptz,
  amens        integer not null default 0,
  reports      integer not null default 0,
  -- hidden by its author or by moderation, kept so the thread does not renumber
  removed      boolean not null default false,
  created_at   timestamptz not null default now(),
  constraint comment_text_shape check (char_length(text) between 1 and 600)
);

create index if not exists comments_song_idx on public.comments (song_id, created_at desc);
create index if not exists comments_author_idx on public.comments (author_id);

create table if not exists public.loves (
  profile_id  uuid not null references public.profiles (id) on delete cascade,
  song_id     text not null references public.songs (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (profile_id, song_id)
);
create index if not exists loves_song_idx on public.loves (song_id);

create table if not exists public.amens (
  profile_id  uuid not null references public.profiles (id) on delete cascade,
  comment_id  text not null references public.comments (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (profile_id, comment_id)
);

create table if not exists public.follows (
  profile_id  uuid not null references public.profiles (id) on delete cascade,
  artist_id   uuid not null references public.profiles (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (profile_id, artist_id),
  constraint no_self_follow check (profile_id <> artist_id)
);
create index if not exists follows_artist_idx on public.follows (artist_id);

create table if not exists public.playlists (
  id          text primary key default ('ply_' || substr(gen_random_uuid()::text, 1, 18)),
  owner_id    uuid not null references public.profiles (id) on delete cascade,
  name        text not null,
  blurb       text not null default '',
  seed        text not null default '',
  accent      text not null default 'jade'
              check (accent in ('jade','gold','turq','madder','cobalt')),
  song_ids    text[] not null default '{}',
  created_at  timestamptz not null default now(),
  constraint playlist_name_shape check (char_length(name) between 1 and 80),
  constraint playlist_size check (coalesce(array_length(song_ids, 1), 0) <= 500)
);
create index if not exists playlists_owner_idx on public.playlists (owner_id);

create table if not exists public.saved_collections (
  profile_id     uuid not null references public.profiles (id) on delete cascade,
  collection_id  text not null references public.collections (id) on delete cascade,
  created_at     timestamptz not null default now(),
  primary key (profile_id, collection_id)
);

create table if not exists public.reports (
  id            text primary key default ('rpt_' || substr(gen_random_uuid()::text, 1, 18)),
  comment_id    text not null references public.comments (id) on delete cascade,
  reporter_id   uuid not null references public.profiles (id) on delete cascade,
  reason        text not null,
  resolved      boolean not null default false,
  resolved_at   timestamptz,
  -- denormalised so the moderation queue reads without three joins
  comment_text  text not null default '',
  author_handle text not null default '',
  song_id       text not null default '',
  song_title    text not null default '',
  created_at    timestamptz not null default now(),
  constraint report_reason_shape check (char_length(reason) between 3 and 300)
);
create index if not exists reports_open_idx on public.reports (created_at desc) where resolved = false;

/* ---------------------------------------------------------------- analytics */

-- One row per listen. This is the only table that grows without bound, so it is the
-- only one with a retention job; the rollups below are what survive.
create table if not exists public.play_events (
  id          bigint generated always as identity primary key,
  song_id     text not null references public.songs (id) on delete cascade,
  profile_id  uuid references public.profiles (id) on delete set null,
  -- anonymous device id, so "listeners" counts people rather than page loads
  client_id   text,
  seconds     integer not null default 0 check (seconds between 0 and 21600),
  completed   boolean not null default false,
  day         date not null default (now() at time zone 'utc')::date,
  created_at  timestamptz not null default now()
);
create index if not exists play_events_song_day_idx on public.play_events (song_id, day desc);
create index if not exists play_events_day_idx on public.play_events (day desc);
create index if not exists play_events_profile_idx on public.play_events (profile_id) where profile_id is not null;

create table if not exists public.song_stats_daily (
  song_id     text not null references public.songs (id) on delete cascade,
  day         date not null,
  plays       integer not null default 0,
  listeners   integer not null default 0,
  seconds     bigint not null default 0,
  primary key (song_id, day)
);
create index if not exists song_stats_day_idx on public.song_stats_daily (day desc);

create table if not exists public.site_stats_daily (
  day         date primary key,
  plays       integer not null default 0,
  listeners   integer not null default 0,
  signups     integer not null default 0
);

/* ------------------------------------------------------------------ helpers */

-- staff check used by policies; security definer so a policy can ask without the
-- caller needing read access to other people's profiles
create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select p.role = 'staff' from public.profiles p where p.id = auth.uid()),
    false
  );
$$;

grant execute on function public.is_staff() to anon, authenticated;

/* --------------------------------------------------------------- auth trigger */

-- Supabase Auth owns credentials; this gives every new user a profile in the same
-- transaction, with a handle derived from their email or their chosen one.
create or replace function public.handle_new_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  wanted text;
  base text;
  final text;
  n integer := 0;
  v_role text := 'listener';
begin
  wanted := lower(coalesce(
    new.raw_user_meta_data ->> 'handle',
    split_part(coalesce(new.email, 'listener'), '@', 1)
  ));
  wanted := regexp_replace(wanted, '[^a-z0-9._]', '', 'g');
  if char_length(wanted) < 3 then
    wanted := 'listener' || substr(new.id::text, 1, 6);
  end if;
  base := left(wanted, 20);
  final := base;

  while exists (select 1 from public.profiles where handle = final)
     or exists (select 1 from public.reserved_handles where handle = final)
  loop
    n := n + 1;
    final := left(base, 16) || lpad(n::text, 4, '0');
  end loop;

  -- a brand-new project has no staff at all: the first account gets it, which is how
  -- you into the moderation queue and the dashboard without touching the SQL editor.
  -- the role is decided before the insert, because the profile guard would put it
  -- back on an update — there is nobody signed in yet for it to recognise as staff
  if not exists (select 1 from public.profiles where role = 'staff') then
    v_role := 'staff';
  end if;

  insert into public.profiles (id, handle, name, seed, city, kind, role)
  values (
    new.id,
    final,
    left(coalesce(new.raw_user_meta_data ->> 'name', final), 48),
    'listener-' || final || '-' || substr(new.id::text, 1, 8),
    left(coalesce(new.raw_user_meta_data ->> 'city', ''), 60),
    'listener',
    v_role
  );

  insert into public.site_stats_daily (day, signups)
  values ((now() at time zone 'utc')::date, 1)
  on conflict (day) do update set signups = public.site_stats_daily.signups + 1;

  return new;
end;
$$;

-- a project that already followed the Supabase docs may have a trigger by this name
drop trigger if exists on_auth_user_created on auth.users;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_profile();

/* --------------------------------------------------------- counter triggers */

create or replace function public.bump_song_likes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.songs set likes = likes + 1 where id = new.song_id;
    return new;
  elsif tg_op = 'DELETE' then
    update public.songs set likes = greatest(likes - 1, 0) where id = old.song_id;
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists loves_counter on public.loves;
create trigger loves_counter
  after insert or delete on public.loves
  for each row execute function public.bump_song_likes();

create or replace function public.bump_song_notes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' and not new.removed then
    update public.songs set notes = notes + 1 where id = new.song_id;
    return new;
  elsif tg_op = 'DELETE' and not old.removed then
    update public.songs set notes = greatest(notes - 1, 0) where id = old.song_id;
    return old;
  elsif tg_op = 'UPDATE' and new.removed <> old.removed then
    if new.removed then
      update public.songs set notes = greatest(notes - 1, 0) where id = new.song_id;
    else
      update public.songs set notes = notes + 1 where id = new.song_id;
    end if;
    return new;
  end if;
  return null;
end;
$$;

drop trigger if exists comments_counter on public.comments;
create trigger comments_counter
  after insert or delete or update of removed on public.comments
  for each row execute function public.bump_song_notes();

create or replace function public.bump_comment_amens()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.comments set amens = amens + 1 where id = new.comment_id;
    return new;
  elsif tg_op = 'DELETE' then
    update public.comments set amens = greatest(amens - 1, 0) where id = old.comment_id;
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists amens_counter on public.amens;
create trigger amens_counter
  after insert or delete on public.amens
  for each row execute function public.bump_comment_amens();

create or replace function public.bump_comment_reports()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.comments set reports = reports + 1 where id = new.comment_id;
    -- three reports is enough to stop the note being shown while staff look at it.
    -- the counter is already the new one at this point, so this reads `reports >= 3`
    -- and not `reports + 1 >= 3` — that off-by-one hid notes at two reports.
    -- the comment guard would otherwise put `removed` back, because inside this
    -- definer trigger the caller is the person who reported it, not a member of staff
    perform public.guard_bypass('three reports');
    update public.comments set removed = true
      where id = new.comment_id and reports >= 3 and not removed;
    return new;
  end if;
  return null;
end;
$$;

drop trigger if exists reports_counter on public.reports;
create trigger reports_counter
  after insert on public.reports
  for each row execute function public.bump_comment_reports();

/* ------------------------------------------------------- write-time guards */

-- RLS says *which rows* you may write; these say *which columns* you may change, so
-- nobody can promote themselves to staff. Counters are not guarded here at all —
-- they are protected by column privileges instead, further down in the RLS
-- migration. The reason is that a BEFORE UPDATE trigger cannot tell a client from
-- the security-definer trigger that maintains the numbers: both arrive as an update,
-- and `auth.uid()` inside a definer function is still whoever called it. Guarding a
-- column that a trigger owns means the trigger's work is silently undone, which is
-- the worst failure there is — a counter that looks maintained and is not.

-- The one column a guard does own and a definer path also writes (`comments.removed`,
-- hidden at three reports) needs a way to say "this is the trigger, not a client".
-- It says so transaction-locally, and no client can reach the function that sets it:
-- execute is revoked from anon and authenticated below.
create or replace function public.guard_bypass(reason text)
returns void
language sql
as $$
  select set_config('coolnasheed.guard', left(coalesce(reason, 'definer'), 40), true)
$$;

create or replace function public.guard_bypassed()
returns boolean
language sql
stable
as $$
  select coalesce(nullif(current_setting('coolnasheed.guard', true), ''), '') <> ''
$$;

revoke execute on function public.guard_bypass(text) from public, anon, authenticated;
grant execute on function public.guard_bypassed() to anon, authenticated;
create or replace function public.guard_profile_columns()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_staff() and old.role is distinct from new.role then
    return new; -- staff may change roles, including their own
  end if;
  new.role := old.role;
  new.kind := old.kind;
  new.verified := old.verified;
  new.created_at := old.created_at;
  new.handle := lower(new.handle);
  if new.handle ~ '[^a-z0-9._]' or char_length(new.handle) not between 3 and 20 then
    raise exception 'That handle is not allowed.' using errcode = '23514';
  end if;
  if exists (select 1 from public.reserved_handles where handle = new.handle) and new.handle <> old.handle then
    raise exception 'That handle belongs to the catalogue itself.' using errcode = '23505';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_guard on public.profiles;
create trigger profiles_guard
  before update on public.profiles
  for each row execute function public.guard_profile_columns();

create or replace function public.guard_song_columns()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.owner_id is distinct from old.owner_id
     and not (public.is_staff() or old.owner_id is null) then
    raise exception 'A nasheed cannot change hands.' using errcode = '42501';
  end if;
  if new.id <> old.id then
    raise exception 'A nasheed id cannot change.' using errcode = '42501';
  end if;
  -- plays, likes, notes and the two timestamps are not writable by anon or
  -- authenticated at all (column privileges, in the RLS migration), so there is
  -- nothing to undo here — and undoing it is what would break the counter triggers
  return new;
end;
$$;

drop trigger if exists songs_guard on public.songs;
create trigger songs_guard
  before update on public.songs
  for each row execute function public.guard_song_columns();

create or replace function public.guard_comment_columns()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- the author may edit the words; only staff, and the three-reports trigger which
  -- announces itself, may take the note off the page
  if new.removed and not old.removed and not public.is_staff() and not public.guard_bypassed() then
    new.removed := false;
    new.text := old.text;
    return new;
  end if;
  if new.author_id <> old.author_id or new.song_id <> old.song_id or new.id <> old.id then
    raise exception 'A note cannot move.' using errcode = '42501';
  end if;
  -- amens, reports and created_at are not writable columns for a client; edited_at is
  -- stamped here so an edit cannot claim it never happened
  if not public.is_staff() and new.text is distinct from old.text then
    new.edited_at := now();
  end if;
  return new;
end;
$$;

drop trigger if exists comments_guard on public.comments;
create trigger comments_guard
  before update on public.comments
  for each row execute function public.guard_comment_columns();



/* ================================================================ 20260914120100_functions.sql */

-- CoolNasheed · reads and writes that belong in the database
--
-- These are Postgres functions called through PostgREST (`supabase.rpc(...)`). They do
-- the work a traditional backend would do — validate a play, roll it up, build a chart,
-- assemble a boot payload — but they cost no Edge Function invocation, have no cold
-- start, and run in one transaction against the data they read.
--
-- The division of labour, stated plainly:
--   Postgres functions  → anything that is a query with rules around it (all of the below)
--   Edge Functions      → anything that needs a secret, a network call, caching in front
--                         of the database, or multipart handling (supabase/functions)

/* -------------------------------------------------------------- play beacon */

-- The single write path for a listen. Validates, inserts the event, rolls it up per
-- song per day, rolls the site up per day, and bumps the song's counter only when the
-- listen was real: fifteen seconds or a completion. A skip should not flatter a track.
create or replace function public.record_play(
  p_song_id text,
  p_seconds integer default 0,
  p_completed boolean default false,
  p_client_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_song public.songs;
  v_profile uuid := auth.uid();
  v_seconds integer;
  v_day date := (now() at time zone 'utc')::date;
  v_client text;
  v_key text;
  v_new_listener boolean := false;
  v_counted boolean;
begin
  select * into v_song from public.songs where id = p_song_id and status = 'live';
  if not found then
    return jsonb_build_object('ok', false, 'error', 'That nasheed is not here.');
  end if;

  v_seconds := least(greatest(coalesce(p_seconds, 0), 0), 21600);
  v_counted := coalesce(p_completed, false) or v_seconds >= 15;
  v_client := nullif(left(coalesce(p_client_id, ''), 64), '');
  v_key := coalesce('u:' || v_profile::text, 'c:' || v_client, 'anon');

  -- a beacon storm should not turn into a chart: one listen per song per five seconds
  if exists (
    select 1 from public.play_events
    where song_id = v_song.id
      and created_at > now() - interval '5 seconds'
      and ((v_profile is not null and profile_id = v_profile) or (v_profile is null and client_id is not distinct from v_client))
  ) then
    return jsonb_build_object('ok', true, 'counted', false, 'duplicate', true, 'plays', v_song.plays);
  end if;

  -- is this listener new to this song today? that is what "listeners" means
  select not exists (
    select 1 from public.play_events
    where song_id = v_song.id and day = v_day
      and coalesce('u:' || profile_id::text, 'c:' || client_id, 'anon') = v_key
  ) into v_new_listener;

  insert into public.play_events (song_id, profile_id, client_id, seconds, completed, day)
  values (v_song.id, v_profile, v_client, v_seconds, coalesce(p_completed, false), v_day);

  insert into public.song_stats_daily (song_id, day, plays, listeners, seconds)
  values (v_song.id, v_day, 1, case when v_new_listener then 1 else 0 end, v_seconds)
  on conflict (song_id, day) do update
    set plays = public.song_stats_daily.plays + 1,
        listeners = public.song_stats_daily.listeners + case when v_new_listener then 1 else 0 end,
        seconds = public.song_stats_daily.seconds + v_seconds;

  insert into public.site_stats_daily (day, plays, listeners)
  values (v_day, 1, case when v_new_listener then 1 else 0 end)
  on conflict (day) do update
    set plays = public.site_stats_daily.plays + 1,
        listeners = public.site_stats_daily.listeners + case when v_new_listener then 1 else 0 end;

  if v_counted then
    update public.songs set plays = plays + 1 where id = v_song.id;
  end if;

  return jsonb_build_object(
    'ok', true,
    'counted', v_counted,
    'plays', (select plays from public.songs where id = v_song.id)
  );
end;
$$;

grant execute on function public.record_play(text, integer, boolean, text) to anon, authenticated;

/* ------------------------------------------------------------------- charts */

create or replace function public.trending(p_window text default '7d', p_limit integer default 10)
returns table (
  song_id text,
  title text,
  accent text,
  maqam text,
  owner_name text,
  plays bigint,
  listeners bigint,
  seconds bigint,
  likes integer
)
language sql
stable
security definer
set search_path = public
as $$
  with bounds as (
    select case p_window
      when '24h' then (now() at time zone 'utc')::date - 1
      when '30d' then (now() at time zone 'utc')::date - 30
      when 'all' then date '1970-01-01'
      else (now() at time zone 'utc')::date - 7
    end as since
  )
  select s.id, s.title, s.accent, s.maqam, p.name,
         sum(d.plays)::bigint, sum(d.listeners)::bigint, sum(d.seconds)::bigint, s.likes
  from public.song_stats_daily d
  join public.songs s on s.id = d.song_id and s.status = 'live'
  left join public.profiles p on p.id = s.owner_id
  cross join bounds b
  where d.day >= b.since
  group by s.id, s.title, s.accent, s.maqam, p.name, s.likes
  order by sum(d.plays) desc, s.likes desc
  limit least(greatest(coalesce(p_limit, 10), 1), 50);
$$;

grant execute on function public.trending(text, integer) to anon, authenticated;

create or replace function public.daily_curve(p_days integer default 14)
returns table (day date, plays integer, listeners integer, signups integer)
language sql
stable
security definer
set search_path = public
as $$
  select d.day::date,
         coalesce(s.plays, 0),
         coalesce(s.listeners, 0),
         coalesce(s.signups, 0)
  from generate_series(
         (now() at time zone 'utc')::date - (least(greatest(coalesce(p_days, 14), 1), 90) - 1),
         (now() at time zone 'utc')::date,
         interval '1 day'
       ) as d(day)
  left join public.site_stats_daily s on s.day = d.day::date
  order by d.day;
$$;

grant execute on function public.daily_curve(integer) to anon, authenticated;

create or replace function public.song_stats(p_song_id text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'plays', coalesce((select plays from public.songs where id = p_song_id), 0),
    'listeners', coalesce((select sum(listeners) from public.song_stats_daily where song_id = p_song_id), 0),
    'seconds', coalesce((select sum(seconds) from public.song_stats_daily where song_id = p_song_id), 0),
    'completed', coalesce((select count(*) from public.play_events where song_id = p_song_id and completed), 0),
    'daily', coalesce((
      select jsonb_agg(jsonb_build_object('day', d.day, 'plays', d.plays, 'listeners', d.listeners) order by d.day)
      from public.song_stats_daily d
      where d.song_id = p_song_id and d.day >= (now() at time zone 'utc')::date - 29
    ), '[]'::jsonb)
  );
$$;

grant execute on function public.song_stats(text) to anon, authenticated;

-- A signed-in listener reads their own history. A signed-out one reads the history of a
-- device id it supplies, which is what makes "recently played" work before you have an
-- account. The id is a random 24-hex string held in localStorage, not a credential: it
-- protects nothing, and the worst it exposes is which nasheeds one anonymous device
-- played. That trade is deliberate, and it is written down here so nobody mistakes it
-- for an oversight.
create or replace function public.my_history(p_limit integer default 30, p_client_id text default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_profile uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 30), 1), 100);
begin
  if v_profile is null and nullif(p_client_id, '') is null then
    return '[]'::jsonb;
  end if;

  return coalesce((
    select jsonb_agg(row_to_json(t)::jsonb order by t."lastAt" desc)
    from (
      select e.song_id as "songId",
             s.title as "title",
             s.accent as "accent",
             p.name as "ownerName",
             count(*)::int as "plays",
             sum(e.seconds)::int as "seconds",
             floor(extract(epoch from max(e.created_at)) * 1000)::bigint as "lastAt"
      from public.play_events e
      join public.songs s on s.id = e.song_id and s.status = 'live'
      left join public.profiles p on p.id = s.owner_id
      where (v_profile is not null and e.profile_id = v_profile)
         or (v_profile is null and e.client_id = nullif(p_client_id, ''))
      group by e.song_id, s.title, s.accent, p.name
      order by 7 desc
      limit v_limit
    ) t
  ), '[]'::jsonb);
end;
$$;

grant execute on function public.my_history(integer, text) to anon, authenticated;

/* ------------------------------------------------------- listening totals */

create or replace function public.my_listening()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'plays', count(*)::int,
    'listenSeconds', coalesce(sum(seconds), 0)::bigint,
    'days', count(distinct day)::int,
    'songs', count(distinct song_id)::int,
    'firstAt', case when min(created_at) is null then null
                    else floor(extract(epoch from min(created_at)) * 1000)::bigint end
  )
  from public.play_events
  where profile_id = auth.uid();
$$;

grant execute on function public.my_listening() to authenticated;

/* ------------------------------------------------------------- boot payloads */

-- One call, everything a cold start needs to draw the home page. The Edge Function
-- `catalog` wraps this with a 60-second cache so a thousand visitors cost one query.
create or replace function public.catalog_payload()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'artists', coalesce((
      select jsonb_agg(jsonb_build_object(
        -- the handle is the public id, so a publisher page reads /yusuf rather than /9f3c…
        'id', p.handle,
        'profileId', p.id,
        'handle', p.handle,
        'name', p.name,
        'nameAr', p.name_ar,
        'role', coalesce(nullif(p.tagline, ''), 'Publisher'),
        'origin', coalesce(nullif(p.city, ''), '—'),
        'bio', p.bio,
        'seed', p.seed,
        'accent', p.accent,
        'verified', p.verified,
        'kind', p.kind,
        'songs', (select count(*)::int from public.songs s where s.owner_id = p.id and s.status = 'live'),
        'followers', (select count(*)::int from public.follows f where f.artist_id = p.id)
      ) order by p.name)
      from public.profiles p
      -- anybody with a live nasheed is a publisher, whether they arrived in the seed
      -- (kind = 'artist') or signed up and used the studio (kind = 'listener')
      where exists (select 1 from public.songs s where s.owner_id = p.id and s.status = 'live')
    ), '[]'::jsonb),
    'songs', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', s.id,
        'ownerId', s.owner_id,
        'ownerHandle', (select handle from public.profiles where id = s.owner_id),
        'title', s.title,
        'titleAr', s.title_ar,
        'note', s.note,
        'maqam', s.maqam,
        'root', s.root,
        'bpm', s.bpm,
        'voices', s.voices,
        'duff', s.duff,
        'duffEnter', s.duff_enter,
        'passes', s.passes,
        'accent', s.accent,
        'year', s.year,
        'tags', to_jsonb(s.tags),
        'lines', s.lines,
        'motifBank', to_jsonb(s.motif_bank),
        'audioPath', s.audio_path,
        'audioMime', s.audio_mime,
        'durationMs', s.duration_ms,
        'artworkPath', s.artwork_path,
        'status', s.status,
        'publishedAt', floor(extract(epoch from s.published_at) * 1000)::bigint,
        'plays', s.plays,
        'likes', s.likes,
        'notes', s.notes
      ) order by s.published_at desc)
      from public.songs s
      where s.status = 'live'
    ), '[]'::jsonb),
    'collections', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', c.id,
        'kind', c.kind,
        'title', c.title,
        'titleAr', c.title_ar,
        'curator', c.curator,
        'blurb', c.blurb,
        'seed', c.seed,
        'accent', c.accent,
        'tags', to_jsonb(c.tags),
        'year', c.year,
        'songIds', to_jsonb(c.song_ids)
      ) order by c.created_at)
      from public.collections c
    ), '[]'::jsonb),
    'tags', coalesce((
      select jsonb_agg(jsonb_build_object('tag', t.tag, 'count', t.count) order by t.count desc, t.tag)
      from (select unnest(tags) as tag, count(*)::int from public.songs where status = 'live' group by 1) t
    ), '[]'::jsonb),
    'generatedAt', floor(extract(epoch from now()) * 1000)::bigint,
    'seeded', exists (select 1 from public.profiles where kind = 'artist' and verified)
  );
$$;

grant execute on function public.catalog_payload() to anon, authenticated;

-- Everything about *you* in one call: profile, counters, loves, follows, sets, what you
-- published and what you have been playing. The client would otherwise fire eight.
create or replace function public.my_bootstrap()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_id uuid := auth.uid();
  v_profile public.profiles;
begin
  if v_id is null then
    return jsonb_build_object('user', null);
  end if;

  select * into v_profile from public.profiles where id = v_id;
  if not found then
    return jsonb_build_object('user', null);
  end if;

  return jsonb_build_object(
    'user', jsonb_build_object(
      'id', v_profile.handle,
      'profileId', v_profile.id,
      'handle', v_profile.handle,
      'name', v_profile.name,
      'nameAr', v_profile.name_ar,
      'tagline', v_profile.tagline,
      'bio', v_profile.bio,
      'city', v_profile.city,
      'seed', v_profile.seed,
      'accent', v_profile.accent,
      'role', v_profile.role,
      'kind', v_profile.kind,
      'verified', v_profile.verified,
      'createdAt', floor(extract(epoch from v_profile.created_at) * 1000)::bigint
    ),
    'stats', jsonb_build_object(
      'published', (select count(*)::int from public.songs s where s.owner_id = v_id and s.status <> 'removed'),
      'notes', (select count(*)::int from public.comments c where c.author_id = v_id),
      'loved', (select count(*)::int from public.loves l where l.profile_id = v_id),
      'playlists', (select count(*)::int from public.playlists p where p.owner_id = v_id),
      'amens', (select count(*)::int from public.amens a where a.profile_id = v_id),
      'followers', (select count(*)::int from public.follows f where f.artist_id = v_id),
      'following', (select count(*)::int from public.follows f where f.profile_id = v_id)
    ) || coalesce(public.my_listening(), '{}'::jsonb),
    'liked', coalesce((select jsonb_agg(l.song_id) from public.loves l where l.profile_id = v_id), '[]'::jsonb),
    'followed', coalesce((select jsonb_agg(f.artist_id::text) from public.follows f where f.profile_id = v_id), '[]'::jsonb),
    'savedCollections', coalesce((select jsonb_agg(sc.collection_id) from public.saved_collections sc where sc.profile_id = v_id), '[]'::jsonb),
    'playlists', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', p.id, 'ownerId', p.owner_id, 'name', p.name, 'blurb', p.blurb,
        'seed', p.seed, 'accent', p.accent, 'songIds', to_jsonb(p.song_ids),
        'createdAt', floor(extract(epoch from p.created_at) * 1000)::bigint
      ) order by p.created_at desc)
      from public.playlists p where p.owner_id = v_id
    ), '[]'::jsonb),
    'songs', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', s.id, 'ownerId', s.owner_id,
        'ownerHandle', (select handle from public.profiles where id = s.owner_id),
        'title', s.title, 'titleAr', s.title_ar,
        'note', s.note, 'maqam', s.maqam, 'root', s.root, 'bpm', s.bpm, 'voices', s.voices,
        'duff', s.duff, 'duffEnter', s.duff_enter, 'passes', s.passes, 'accent', s.accent,
        'year', s.year, 'tags', to_jsonb(s.tags), 'lines', s.lines, 'motifBank', to_jsonb(s.motif_bank),
        'audioPath', s.audio_path, 'audioMime', s.audio_mime, 'durationMs', s.duration_ms,
        'artworkPath', s.artwork_path, 'status', s.status,
        'publishedAt', floor(extract(epoch from s.published_at) * 1000)::bigint,
        'plays', s.plays, 'likes', s.likes, 'notes', s.notes
      ) order by s.published_at desc)
      from public.songs s where s.owner_id = v_id and s.status <> 'removed'
    ), '[]'::jsonb),
    'history', public.my_history(40, null)
  );
end;
$$;

grant execute on function public.my_bootstrap() to authenticated;

create or replace function public.publisher_profile(p_id text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_profile public.profiles;
  v_id uuid := null;
begin
  -- publishers are addressed by handle (/yusuf); a bare uuid still works
  select * into v_profile from public.profiles where handle = lower(coalesce(p_id, ''));
  if not found and p_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
    v_id := p_id::uuid;
    select * into v_profile from public.profiles where id = v_id;
  end if;
  if not found then
    return null;
  end if;
  v_id := v_profile.id;

  return jsonb_build_object(
    'user', jsonb_build_object(
      'id', v_profile.handle, 'profileId', v_profile.id,
      'handle', v_profile.handle, 'name', v_profile.name,
      'nameAr', v_profile.name_ar, 'tagline', v_profile.tagline, 'bio', v_profile.bio, 'city', v_profile.city,
      'seed', v_profile.seed, 'accent', v_profile.accent, 'role', v_profile.role,
      'kind', v_profile.kind, 'verified', v_profile.verified,
      'createdAt', floor(extract(epoch from v_profile.created_at) * 1000)::bigint
    ),
    'followers', (select count(*)::int from public.follows f where f.artist_id = v_id),
    'youFollow', coalesce(
      (select count(*) > 0 from public.follows f
        where f.artist_id = v_id and f.profile_id = auth.uid()), false),
    'songs', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', s.id, 'ownerId', s.owner_id,
        'ownerHandle', (select handle from public.profiles where id = s.owner_id),
        'title', s.title, 'titleAr', s.title_ar,
        'note', s.note, 'maqam', s.maqam, 'root', s.root, 'bpm', s.bpm, 'voices', s.voices,
        'duff', s.duff, 'duffEnter', s.duff_enter, 'passes', s.passes, 'accent', s.accent,
        'year', s.year, 'tags', to_jsonb(s.tags), 'lines', s.lines, 'motifBank', to_jsonb(s.motif_bank),
        'audioPath', s.audio_path, 'audioMime', s.audio_mime, 'durationMs', s.duration_ms,
        'artworkPath', s.artwork_path, 'status', s.status,
        'publishedAt', floor(extract(epoch from s.published_at) * 1000)::bigint,
        'plays', s.plays, 'likes', s.likes, 'notes', s.notes
      ) order by s.published_at desc)
      from public.songs s where s.owner_id = v_id and s.status = 'live'
    ), '[]'::jsonb),
    'totals', coalesce((
      select jsonb_build_object('plays', sum(s.plays)::int, 'likes', sum(s.likes)::int, 'notes', sum(s.notes)::int)
      from public.songs s where s.owner_id = v_id and s.status = 'live'
    ), jsonb_build_object('plays', 0, 'likes', 0, 'notes', 0))
  );
end;
$$;

grant execute on function public.publisher_profile(text) to anon, authenticated;

/* --------------------------------------------------------------- moderation */

create or replace function public.report_comment(p_comment_id text, p_reason text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_comment public.comments;
  v_song public.songs;
  v_id uuid := auth.uid();
begin
  if v_id is null then
    raise exception 'You need an account to report a note.' using errcode = '42501';
  end if;
  if char_length(coalesce(p_reason, '')) not between 3 and 300 then
    raise exception 'A reason between 3 and 300 characters, please.' using errcode = '22023';
  end if;

  select * into v_comment from public.comments where id = p_comment_id and not removed;
  if not found then
    raise exception 'That note is gone.' using errcode = 'P0002';
  end if;
  select * into v_song from public.songs where id = v_comment.song_id;

  insert into public.reports (comment_id, reporter_id, reason, comment_text, author_handle, song_id, song_title)
  values (
    v_comment.id, v_id, p_reason, left(v_comment.text, 600),
    coalesce((select handle from public.profiles where id = v_comment.author_id), ''),
    coalesce(v_song.id, ''), coalesce(v_song.title, '')
  );

  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.report_comment(text, text) to authenticated;

-- Resolve a report, optionally hiding the note it was about. Staff only.
create or replace function public.resolve_report(p_report_id text, p_hide boolean default false)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_report public.reports;
begin
  if not public.is_staff() then
    raise exception 'That is a staff-only action.' using errcode = '42501';
  end if;

  select * into v_report from public.reports where id = p_report_id;
  if not found then
    raise exception 'No such report.' using errcode = 'P0002';
  end if;

  update public.reports set resolved = true, resolved_at = now() where id = p_report_id;

  -- Staff have two answers: "this note goes" and "this note stands". Three reports
  -- hide a note on their own, so closing a report as unfounded has to be able to put
  -- the note back — otherwise something the trigger hid stays hidden and the way back
  -- is a second action nobody would think to take. The words stay in the row either
  -- way; `removed` is what decides whether the room can see it.
  update public.comments
     set removed = p_hide
   where id = v_report.comment_id
     and removed is distinct from p_hide;

  return jsonb_build_object('ok', true, 'hid', p_hide);
end;
$$;

grant execute on function public.resolve_report(text, boolean) to authenticated;

/* ------------------------------------------------------------------ dashboard */

create or replace function public.admin_summary(p_days integer default 14)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_staff() then
    raise exception 'That is a staff-only page.' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'totals', jsonb_build_object(
      'users', (select count(*)::int from public.profiles where kind = 'listener'),
      'artists', (select count(*)::int from public.profiles where kind = 'artist'),
      'songs', (select count(*)::int from public.songs where status = 'live'),
      'removed', (select count(*)::int from public.songs where status = 'removed'),
      'plays', (select coalesce(sum(plays), 0)::bigint from public.song_stats_daily),
      'listenSeconds', (select coalesce(sum(seconds), 0)::bigint from public.song_stats_daily),
      'notes', (select count(*)::int from public.comments where not removed),
      'likes', (select count(*)::int from public.loves),
      'amens', (select count(*)::int from public.amens),
      'reportsOpen', (select count(*)::int from public.reports where not resolved),
      'storageBytes', (select coalesce(sum((metadata ->> 'size')::bigint), 0) from storage.objects
                        where bucket_id in ('nasheed-audio','nasheed-artwork'))
    ),
    'daily', (select coalesce(jsonb_agg(jsonb_build_object(
                'day', d.day, 'plays', d.plays, 'listeners', d.listeners, 'signups', d.signups) order by d.day), '[]'::jsonb)
              from public.daily_curve(p_days) d),
    'topSongs', (select coalesce(jsonb_agg(jsonb_build_object(
                'songId', t.song_id, 'title', t.title, 'ownerName', t.owner_name,
                'plays', t.plays, 'listeners', t.listeners, 'seconds', t.seconds, 'likes', t.likes) order by t.plays desc), '[]'::jsonb)
              from public.trending('30d', 10) t),
    'topOwners', coalesce((
      select jsonb_agg(jsonb_build_object(
        'ownerId', o.owner_id, 'name', o.name, 'handle', o.handle,
        'songs', o.songs, 'plays', o.plays) order by o.plays desc)
      from (
        select s.owner_id, p.name, p.handle, count(s.id)::int as songs, coalesce(sum(s.plays), 0)::bigint as plays
        from public.songs s
        join public.profiles p on p.id = s.owner_id
        where s.status = 'live' and s.owner_id is not null
        group by s.owner_id, p.name, p.handle
        order by plays desc
        limit 8
      ) o
    ), '[]'::jsonb),
    'reports', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', r.id, 'commentId', r.comment_id, 'reporterId', r.reporter_id, 'reason', r.reason,
        'createdAt', floor(extract(epoch from r.created_at) * 1000)::bigint, 'resolved', r.resolved,
        'commentText', r.comment_text, 'authorHandle', r.author_handle,
        'songId', r.song_id, 'songTitle', r.song_title) order by r.created_at desc)
      from public.reports r
      where not r.resolved
      limit 50
    ), '[]'::jsonb),
    'recentSongs', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', s.id, 'title', s.title, 'owner', p.handle, 'hasAudio', s.audio_path is not null,
        'status', s.status, 'plays', s.plays,
        'publishedAt', floor(extract(epoch from s.published_at) * 1000)::bigint) order by s.published_at desc)
      from public.songs s
      left join public.profiles p on p.id = s.owner_id
      limit 25
    ), '[]'::jsonb)
  );
end;
$$;

grant execute on function public.admin_summary(integer) to authenticated;

/* ------------------------------------------------------------------ retention */

-- The rollups are the history; the raw events are only needed for recent detail. Keeping
-- 90 days of them is what keeps a free-tier database under its 500 MB ceiling forever.
create or replace function public.prune_play_events(p_keep_days integer default 90)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows integer;
begin
  delete from public.play_events
  where day < (now() at time zone 'utc')::date - least(greatest(coalesce(p_keep_days, 90), 7), 365);
  get diagnostics v_rows = row_count;
  return v_rows;
end;
$$;

-- only the service role (or a scheduled job) may prune
revoke execute on function public.prune_play_events(integer) from public;
grant execute on function public.prune_play_events(integer) to service_role;

-- pg_cron is available on the free tier; if it is not enabled on your project this
-- block fails quietly and you can run `select public.prune_play_events()` by hand.
do $body$
begin
  create extension if not exists pg_cron with schema pg_catalog;
  perform cron.schedule(
    'coolnasheed-prune-play-events',
    '17 3 * * *',
    'select public.prune_play_events(90)'
  );
exception when others then
  raise notice 'pg_cron unavailable (%), skipping the retention schedule', sqlerrm;
end;
$body$;



/* ================================================================ 20260914120300_rls.sql */

-- ---------------------------------------------------------------------------
--  Cool Nasheed · migration 3: row level security
--
--  The rule of the house:
--    · anyone, account or not, can read what is published and count it;
--    · a listener writes only rows that belong to them;
--    · a publisher manages what they published;
--    · staff manage everything;
--    · nobody edits a counter, a role or a verified flag by hand — those move
--      through the triggers and stored procedures in the migrations before this.
-- ---------------------------------------------------------------------------

alter table public.profiles           enable row level security;
alter table public.songs              enable row level security;
alter table public.collections        enable row level security;
alter table public.comments           enable row level security;
alter table public.loves              enable row level security;
alter table public.amens              enable row level security;
alter table public.follows            enable row level security;
alter table public.playlists          enable row level security;
alter table public.saved_collections  enable row level security;
alter table public.reports            enable row level security;
alter table public.play_events        enable row level security;
alter table public.song_stats_daily   enable row level security;
alter table public.site_stats_daily   enable row level security;
alter table public.reserved_handles   enable row level security;

-- ------------------------------- profiles ----------------------------------
-- readable by everyone: a publisher page is a public page.
-- writable by nobody at insert time — the auth.users trigger makes the row.

drop policy if exists "profiles are public" on public.profiles;
create policy "profiles are public"
  on public.profiles for select to anon, authenticated
  using (true);

drop policy if exists "you may edit your own profile" on public.profiles;
create policy "you may edit your own profile"
  on public.profiles for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

drop policy if exists "staff may remove a profile" on public.profiles;
create policy "staff may remove a profile"
  on public.profiles for delete to authenticated
  using (id = auth.uid() or public.is_staff());

-- -------------------------------- songs ------------------------------------

drop policy if exists "live nasheeds are public" on public.songs;
create policy "live nasheeds are public"
  on public.songs for select to anon, authenticated
  using (
    status = 'live'
    or owner_id = auth.uid()
    or public.is_staff()
  );

drop policy if exists "a publisher may add their own nasheed" on public.songs;
create policy "a publisher may add their own nasheed"
  on public.songs for insert to authenticated
  with check (owner_id = auth.uid());

drop policy if exists "a publisher may edit their own nasheed" on public.songs;
create policy "a publisher may edit their own nasheed"
  on public.songs for update to authenticated
  using (owner_id = auth.uid() or public.is_staff())
  with check (owner_id = auth.uid() or public.is_staff());

drop policy if exists "a publisher may remove their own nasheed" on public.songs;
create policy "a publisher may remove their own nasheed"
  on public.songs for delete to authenticated
  using (owner_id = auth.uid() or public.is_staff());

-- ------------------------------ collections --------------------------------
-- shelves are curated, so they are simply public; only their owner or staff write

drop policy if exists "collections are public" on public.collections;
create policy "collections are public"
  on public.collections for select to anon, authenticated
  using (true);

drop policy if exists "a curator may add a collection" on public.collections;
create policy "a curator may add a collection"
  on public.collections for insert to authenticated
  with check (owner_id = auth.uid() or public.is_staff());

drop policy if exists "a curator may edit their collection" on public.collections;
create policy "a curator may edit their collection"
  on public.collections for update to authenticated
  using (owner_id = auth.uid() or public.is_staff())
  with check (owner_id = auth.uid() or public.is_staff());

drop policy if exists "a curator may remove their collection" on public.collections;
create policy "a curator may remove their collection"
  on public.collections for delete to authenticated
  using (owner_id = auth.uid() or public.is_staff());

-- ------------------------------- comments ----------------------------------
-- a note under your own nasheed is yours to look after, which is why its publisher
-- can see and remove it even when it is hidden from the room

drop policy if exists "notes are public unless removed" on public.comments;
create policy "notes are public unless removed"
  on public.comments for select to anon, authenticated
  using (
    removed = false
    or author_id = auth.uid()
    or public.is_staff()
    or exists (
      select 1 from public.songs s
      where s.id = comments.song_id and s.owner_id = auth.uid()
    )
  );

drop policy if exists "a listener may leave a note" on public.comments;
create policy "a listener may leave a note"
  on public.comments for insert to authenticated
  with check (author_id = auth.uid());

drop policy if exists "a listener may edit their own note" on public.comments;
create policy "a listener may edit their own note"
  on public.comments for update to authenticated
  using (
    author_id = auth.uid()
    or public.is_staff()
    or exists (
      select 1 from public.songs s
      where s.id = comments.song_id and s.owner_id = auth.uid()
    )
  )
  with check (
    author_id = auth.uid()
    or public.is_staff()
    or exists (
      select 1 from public.songs s
      where s.id = comments.song_id and s.owner_id = auth.uid()
    )
  );

drop policy if exists "a listener may delete their own note" on public.comments;
create policy "a listener may delete their own note"
  on public.comments for delete to authenticated
  using (
    author_id = auth.uid()
    or public.is_staff()
    or exists (
      select 1 from public.songs s
      where s.id = comments.song_id and s.owner_id = auth.uid()
    )
  );

-- -------------------------------- loves ------------------------------------
-- what you loved is yours; the room only ever sees the count

drop policy if exists "loves are yours" on public.loves;
create policy "loves are yours"
  on public.loves for select to authenticated
  using (profile_id = auth.uid() or public.is_staff());

drop policy if exists "a listener may love a nasheed" on public.loves;
create policy "a listener may love a nasheed"
  on public.loves for insert to authenticated
  with check (profile_id = auth.uid());

drop policy if exists "a listener may take their love back" on public.loves;
create policy "a listener may take their love back"
  on public.loves for delete to authenticated
  using (profile_id = auth.uid() or public.is_staff());

-- -------------------------------- amens ------------------------------------
-- saying amin to somebody's duʿā is a public act, so the row is public too

drop policy if exists "amens are public encouragement" on public.amens;
create policy "amens are public encouragement"
  on public.amens for select to anon, authenticated
  using (true);

drop policy if exists "a listener may say amin" on public.amens;
create policy "a listener may say amin"
  on public.amens for insert to authenticated
  with check (profile_id = auth.uid());

drop policy if exists "a listener may take their amin back" on public.amens;
create policy "a listener may take their amin back"
  on public.amens for delete to authenticated
  using (profile_id = auth.uid() or public.is_staff());

-- ------------------------------- follows -----------------------------------

drop policy if exists "follows are public" on public.follows;
create policy "follows are public"
  on public.follows for select to anon, authenticated
  using (true);

drop policy if exists "a listener may follow a publisher" on public.follows;
create policy "a listener may follow a publisher"
  on public.follows for insert to authenticated
  with check (profile_id = auth.uid() and profile_id <> artist_id);

drop policy if exists "a listener may unfollow" on public.follows;
create policy "a listener may unfollow"
  on public.follows for delete to authenticated
  using (profile_id = auth.uid() or public.is_staff());

-- ------------------------------- playlists ---------------------------------

drop policy if exists "playlists are yours" on public.playlists;
create policy "playlists are yours"
  on public.playlists for select to authenticated
  using (owner_id = auth.uid() or public.is_staff());

drop policy if exists "a listener may build a playlist" on public.playlists;
create policy "a listener may build a playlist"
  on public.playlists for insert to authenticated
  with check (owner_id = auth.uid());

drop policy if exists "a listener may edit their playlist" on public.playlists;
create policy "a listener may edit their playlist"
  on public.playlists for update to authenticated
  using (owner_id = auth.uid() or public.is_staff())
  with check (owner_id = auth.uid() or public.is_staff());

drop policy if exists "a listener may remove their playlist" on public.playlists;
create policy "a listener may remove their playlist"
  on public.playlists for delete to authenticated
  using (owner_id = auth.uid() or public.is_staff());

-- --------------------------- saved collections -----------------------------

drop policy if exists "saved collections are yours" on public.saved_collections;
create policy "saved collections are yours"
  on public.saved_collections for select to authenticated
  using (profile_id = auth.uid() or public.is_staff());

drop policy if exists "a listener may save a collection" on public.saved_collections;
create policy "a listener may save a collection"
  on public.saved_collections for insert to authenticated
  with check (profile_id = auth.uid());

drop policy if exists "a listener may unsave a collection" on public.saved_collections;
create policy "a listener may unsave a collection"
  on public.saved_collections for delete to authenticated
  using (profile_id = auth.uid() or public.is_staff());

-- -------------------------------- reports ----------------------------------

drop policy if exists "a report is between its author and staff" on public.reports;
create policy "a report is between its author and staff"
  on public.reports for select to authenticated
  using (reporter_id = auth.uid() or public.is_staff());

drop policy if exists "a listener may report a note they did not write" on public.reports;
create policy "a listener may report a note they did not write"
  on public.reports for insert to authenticated
  with check (
    reporter_id = auth.uid()
    and not exists (
      select 1 from public.comments c
      where c.id = comment_id and c.author_id = auth.uid()
    )
  );

drop policy if exists "staff resolve reports" on public.reports;
create policy "staff resolve reports"
  on public.reports for update to authenticated
  using (public.is_staff())
  with check (public.is_staff());

drop policy if exists "staff may clear reports" on public.reports;
create policy "staff may clear reports"
  on public.reports for delete to authenticated
  using (public.is_staff());

-- ------------------------------ play events --------------------------------
-- anonymous beacons arrive through record_play(), which is security definer and so
-- writes past RLS; a signed-in listener may also write their own row directly.

drop policy if exists "you see your own listening" on public.play_events;
create policy "you see your own listening"
  on public.play_events for select to authenticated
  using (profile_id = auth.uid() or public.is_staff());

drop policy if exists "a listener may record their own play" on public.play_events;
create policy "a listener may record their own play"
  on public.play_events for insert to authenticated
  with check (profile_id = auth.uid());

drop policy if exists "staff may clear play events" on public.play_events;
create policy "staff may clear play events"
  on public.play_events for delete to authenticated
  using (public.is_staff());

-- --------------------------------- rollups ---------------------------------
-- the charts are public information; only stored procedures write them

drop policy if exists "daily nasheed stats are public" on public.song_stats_daily;
create policy "daily nasheed stats are public"
  on public.song_stats_daily for select to anon, authenticated
  using (true);

drop policy if exists "daily site stats are public" on public.site_stats_daily;
create policy "daily site stats are public"
  on public.site_stats_daily for select to anon, authenticated
  using (true);

-- --------------------------- reserved handles ------------------------------

drop policy if exists "staff manage reserved handles" on public.reserved_handles;
create policy "staff manage reserved handles"
  on public.reserved_handles for all to authenticated
  using (public.is_staff())
  with check (public.is_staff());

-- --------------------------------- grants ----------------------------------
-- RLS decides *which* rows; these decide *whether you may ask at all*

grant usage on schema public to anon, authenticated, service_role;

grant select on
  public.profiles, public.songs, public.collections, public.comments,
  public.amens, public.follows, public.song_stats_daily, public.site_stats_daily
  to anon;

grant select, insert, update, delete on
  public.profiles, public.songs, public.collections, public.comments,
  public.loves, public.amens, public.follows, public.playlists,
  public.saved_collections, public.reports, public.play_events,
  public.reserved_handles
  to authenticated;

grant select on
  public.profiles, public.songs, public.collections, public.comments,
  public.amens, public.follows, public.song_stats_daily, public.site_stats_daily
  to authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;

-- ------------------------------ column privileges ---------------------------
-- RLS decides which rows; these decide which columns. A counter is maintained by a
-- trigger, and the trigger that owns a column must be the only thing writing it.
--
-- In Postgres a table-level GRANT covers every column, and REVOKE (column) only
-- cancels a column-level grant — it does not subtract from the table-level one. So
-- the counters are closed by taking the table-level privilege back and re-granting
-- it column by column, leaving out the ones the database owns. The security-definer
-- triggers and functions that do the counting run as the table owner, so they never
-- notice; a client that tries gets "permission denied for column plays", which is a
-- better answer than a BEFORE trigger quietly putting the old value back.

revoke insert, update on public.songs from authenticated;
grant insert (
  owner_id, title, title_ar, note, maqam, root, bpm, voices, duff, duff_enter,
  passes, accent, year, tags, lines, motif_bank, audio_path, audio_mime,
  audio_bytes, duration_ms, artwork_path, status
) on public.songs to authenticated;
grant update (
  title, title_ar, note, maqam, root, bpm, voices, duff, duff_enter, passes,
  accent, year, tags, lines, motif_bank, audio_path, audio_mime, audio_bytes,
  duration_ms, artwork_path, status
) on public.songs to authenticated;
-- id, owner_id, plays, likes, notes, published_at and created_at are not writable

revoke insert, update on public.comments from authenticated;
grant insert (song_id, author_id, text, at_line) on public.comments to authenticated;
grant update (text, removed) on public.comments to authenticated;
-- amens, reports, created_at and edited_at belong to the triggers

-- the play beacon is the only door into the analytics: it dedupes, decides what
-- counts as a listen and maintains the rollups in one place. Writing events by hand
-- would produce history with no chart behind it. (Clearing your own history is a
-- feature that does not exist yet; when it does, it gets its own RPC.)
revoke insert, update, delete on public.play_events from anon, authenticated;

-- reserved handles belong to the catalogue; a client may read them, never move them
revoke insert, update, delete on public.reserved_handles from anon, authenticated;

-- the daily rollups are select-only for everybody: they were never granted write
-- access above, and record_play() maintains them as the table owner.

-- realtime: notes and counters appear in an open room without anybody refreshing
do $body$
begin
  alter publication supabase_realtime add table public.comments;
  alter publication supabase_realtime add table public.amens;
  alter publication supabase_realtime add table public.songs;
exception when others then
  raise notice 'supabase_realtime publication unavailable (%), skipping', sqlerrm;
end;
$body$;



/* ================================================================ 20260914120400_storage.sql */

-- ---------------------------------------------------------------------------
--  Cool Nasheed · migration 4: storage
--
--  Two public buckets. Public means the file is served straight from
--  Supabase's storage CDN with no function in the way, so a listener streaming
--  a nasheed costs nothing from the Edge Function allowance.
--
--    nasheed-audio    <uid>/<songId>.<ext>   ≤ 60 MB, audio only
--    nasheed-artwork  <uid>/<name>.<ext>     ≤  8 MB, images only
--
--  Size and MIME limits live on the bucket, so the storage API rejects bad
--  uploads before RLS is even consulted. The policies only answer one
--  question: does this path belong to you?
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('nasheed-audio', 'nasheed-audio', true, 62914560, array[
    'audio/mpeg', 'audio/mp3', 'audio/wav', 'audio/x-wav', 'audio/wave',
    'audio/ogg', 'audio/opus', 'audio/mp4', 'audio/m4a', 'audio/x-m4a',
    'audio/aac', 'audio/webm', 'audio/flac'
  ]),
  ('nasheed-artwork', 'nasheed-artwork', true, 8388608, array[
    'image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/avif', 'image/svg+xml'
  ])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- ------------------------------ read ---------------------------------------

drop policy if exists "nasheed audio is public" on storage.objects;
create policy "nasheed audio is public"
  on storage.objects for select to anon, authenticated
  using (bucket_id = 'nasheed-audio');

drop policy if exists "nasheed artwork is public" on storage.objects;
create policy "nasheed artwork is public"
  on storage.objects for select to anon, authenticated
  using (bucket_id = 'nasheed-artwork');

-- ------------------------------ write --------------------------------------
-- every object lives under the uploader's own uid folder

drop policy if exists "a publisher uploads into their own audio folder" on storage.objects;
create policy "a publisher uploads into their own audio folder"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'nasheed-audio'
    and split_part(name, '/', 1) = auth.uid()::text
  );

drop policy if exists "a publisher uploads into their own artwork folder" on storage.objects;
create policy "a publisher uploads into their own artwork folder"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'nasheed-artwork'
    and split_part(name, '/', 1) = auth.uid()::text
  );

drop policy if exists "a publisher may replace files in their own audio folder" on storage.objects;
create policy "a publisher may replace files in their own audio folder"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'nasheed-audio'
    and split_part(name, '/', 1) = auth.uid()::text
  )
  with check (
    bucket_id = 'nasheed-audio'
    and split_part(name, '/', 1) = auth.uid()::text
  );

drop policy if exists "a publisher may replace files in their own artwork folder" on storage.objects;
create policy "a publisher may replace files in their own artwork folder"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'nasheed-artwork'
    and split_part(name, '/', 1) = auth.uid()::text
  )
  with check (
    bucket_id = 'nasheed-artwork'
    and split_part(name, '/', 1) = auth.uid()::text
  );

drop policy if exists "a publisher may delete their own audio" on storage.objects;
create policy "a publisher may delete their own audio"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'nasheed-audio'
    and (split_part(name, '/', 1) = auth.uid()::text or public.is_staff())
  );

drop policy if exists "a publisher may delete their own artwork" on storage.objects;
create policy "a publisher may delete their own artwork"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'nasheed-artwork'
    and (split_part(name, '/', 1) = auth.uid()::text or public.is_staff())
  );
-- Clients derive public URLs themselves with
-- supabase.storage.from('nasheed-audio').getPublicUrl(path), so nothing here needs
-- to know the project host.

